# Control 13/03/17
Fill in code in the cells below, answering the questions.

1/ Make a list (call it "days") with the number of days in each month of the year, 31, 28, 30...

2/ Calculate the average number of days in a month:

3/ Calculate the variance in the length of months:

# Tutorial
## Preliminaries
Before processing the images we need to set up the tools and load the data. We need to import several packages, so before running this notebook you should create an environment (conda or virtualenv) with matplotlib, numpy, and scikit-image, and jupyter. For example:

`conda create env -n BIO399E jupyter matplotlib numpy scipy scikit-image`

and then activate it, e.g. on Mac/Linux:

`source activate BIO399E`

or on windows

`activate BIO399E`

or select the conda env here in Jupyter.

## Modules
First import the standard tools, numpy and matplotlib. These are very well documented packages, more info can be found here:

http://www.matplotlib.org

http://www.numpy.org

In [7]:
import numpy as np
import matplotlib

## Numpy arrays
Lists are a simple way to store collections of data, but they are not very flexible. To deal with numerical data it is better is to use a package called numpy, which stores data in n-dimensional arrays. The simplest is a lot like a list, and we can make it from a list:


In [17]:
days = [31,28,30]
adays = np.array(days)
print adays

[31 28 30]


We can also make an array from scratch and fill it with zeros:

In [16]:
x = np.zeros((12,))
print x

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


Now we have the days in a numpy array we can use functions from numpy to easily do the control:

In [22]:
average_days = adays.mean()
print average_days

29.6666666667


In [23]:
var_days = adays.var()
print var_days

1.55555555556


### 2-dimensional arrays
Numpy can handle arrays of any number dimensions. For example for images we will use 2-dimensional arrays (in a later class). Here is how to make a 2-d array:

In [28]:
twod = np.zeros((5,5))
print twod

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


## Exercise 1
Numpy has many functions that perform calculations on arrays, see here 